function cleanOneLine(value) {
  return String(value || "")
    .replace(/[\t\r\n]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function escapeMarkdownCell(value) {
  return cleanOneLine(value).replace(/\|/g, "\\|");
}

function formatDate(value = new Date()) {
  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) return new Date().toISOString();
  return date.toISOString();
}

export function buildQuickStatementsReviewDraft(items, options = {}) {
  const entityId = cleanOneLine(options.entityId || items?.[0]?.entityId || "");
  const entityLabel = cleanOneLine(options.entityLabel || entityId || "Selected entity");
  const createdAt = formatDate(options.createdAt);
  const rows = Array.isArray(items) ? items : [];

  const lines = [
    "# QuickStatements review draft generated by Wikidata Explorer",
    `# Entity: ${entityLabel}${entityId ? ` (${entityId})` : ""}`,
    `# Created: ${createdAt}`,
    "# Mode: draft-only; every row is commented out and safe to paste for review.",
    "# Complete source values, duplicate checks, and community/bot approvals before turning any row into a live edit.",
    "#",
    "# Suggested columns: item<TAB>property<TAB>value<TAB>source-property<TAB>source-value<TAB>edit-summary",
  ];

  if (!rows.length) {
    lines.push("# No review queue items were available for export.");
    return `${lines.join("\n")}\n`;
  }

  for (const item of rows) {
    const id = cleanOneLine(item.entityId || entityId);
    const propertyId = cleanOneLine(item.propertyId);
    const value = cleanOneLine(item.value || "VALUE_TO_VERIFY");
    const title = cleanOneLine(item.title);
    const detail = cleanOneLine(item.detail);
    const severity = cleanOneLine(item.severity || "medium");
    lines.push(`# ${id}\t${propertyId}\t${value}\tS248\tSOURCE_TO_ADD\t${severity}: ${title}`);
    if (detail) lines.push(`# note: ${detail}`);
  }

  return `${lines.join("\n")}\n`;
}

export function buildReviewMarkdownExport(items, options = {}) {
  const entityId = cleanOneLine(options.entityId || items?.[0]?.entityId || "");
  const entityLabel = cleanOneLine(options.entityLabel || entityId || "Selected entity");
  const createdAt = formatDate(options.createdAt);
  const rows = Array.isArray(items) ? items : [];

  const lines = [
    `# Wikidata Review Queue: ${entityLabel}${entityId ? ` (${entityId})` : ""}`,
    "",
    `Generated: ${createdAt}`,
    "",
    "This is a draft curation artifact. It does not perform edits and should be checked against Wikidata constraints, references, duplicate statements, and bot/community approval requirements before use.",
    "",
  ];

  if (!rows.length) {
    lines.push("No review queue items were available for export.", "");
    return lines.join("\n");
  }

  lines.push("| Severity | Property | Value | Finding | Next action |", "| --- | --- | --- | --- | --- |");
  for (const item of rows) {
    lines.push(`| ${escapeMarkdownCell(item.severity)} | ${escapeMarkdownCell(`${item.propertyLabel || item.propertyId} (${item.propertyId})`)} | ${escapeMarkdownCell(item.value)} | ${escapeMarkdownCell(item.title)} | ${escapeMarkdownCell(item.detail)} |`);
  }

  lines.push("", "## Safety Checklist", "", "- Confirm each target item and property ID.", "- Add reliable sources before live edits.", "- Check duplicate statements and Wikidata constraints.", "- Keep batch size small and review edit summaries.", "- Use approved bot tasks/accounts for automated writes.", "");
  return lines.join("\n");
}
